src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Article;


#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(options: ['unsigned' => true])]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $SectionTitle = null;

    #[ORM\Column(length: 105)]
    private ?string $SectionSlug = null;

    #[ORM\Column(length: 500)]
    private ?string $SectionDetail = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSectionTitle(): ?string
    {
        return $this->SectionTitle;
    }

    public function setSectionTitle(string $SectionTitle): static
    {
        $this->SectionTitle = $SectionTitle;

        return $this;
    }

    public function getSectionSlug(): ?string
    {
        return $this->SectionSlug;
    }

    public function setSectionSlug(string $SectionSlug): static
    {
        $this->SectionSlug = $SectionSlug;

        return $this;
    }

    public function getSectionDetail(): ?string
    {
        return $this->SectionDetail;
    }

    public function setSectionDetail(string $SectionDetail): static
    {
        $this->SectionDetail = $SectionDetail;

        return $this;
    }
    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'sections')]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addSection($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeSection($this);
        }

        return $this;
    }
    

}

templates/partials/nav.html.twig
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">BLOG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('homepage') }}">Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                    {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item"><a class="nav-link" href="{{ path('app_login') }}">Login</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ path('app_logout') }}">Logout</a></li>
                    {% endif %}
                    {# et si on est admin #}
                    {% if is_granted("ROLE_ADMIN") %}
                    <li class="nav-item"><a class="nav-link" href="/admin">Administration</a></li>
                    {% endif %}
                    {% for section in sections %}
    <li class="nav-item">
        <a class="nav-link text-warning" href="{{ path('section', {slug: section.sectionSlug}) }}">
            {{ section.sectionTitle }}
        </a>
    </li>
{% endfor %}
                <!--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>-->
            </ul>
        </div>
    </div>
</nav>