src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(options: ['unsigned' => true])]
    private ?int $id = null;

    #[ORM\Column(length: 160)]
    private ?string $Title = null;

    #[ORM\Column(length: 162)]
    private ?string $TitleSlug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Text = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $ArticleDateCreate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $ArticleDatePosted = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ["default" => false])]
    private ?bool $Published = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getTitleSlug(): ?string
    {
        return $this->TitleSlug;
    }

    public function setTitleSlug(string $TitleSlug): static
    {
        $this->TitleSlug = $TitleSlug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->Text;
    }

    public function setText(string $Text): static
    {
        $this->Text = $Text;

        return $this;
    }

    public function getArticleDateCreate(): ?\DateTimeInterface
    {
        return $this->ArticleDateCreate;
    }

    public function setArticleDateCreate(\DateTimeInterface $ArticleDateCreate): static
    {
        $this->ArticleDateCreate = $ArticleDateCreate;

        return $this;
    }

    public function getArticleDatePosted(): ?\DateTimeInterface
    {
        return $this->ArticleDatePosted;
    }

    public function setArticleDatePosted(?\DateTimeInterface $ArticleDatePosted): static
    {
        $this->ArticleDatePosted = $ArticleDatePosted;
    
        return $this;
    }


    public function getPublished(): ?bool
    {
        return $this->Published;
    }

    public function setPublished(bool $Published): static
    {
        $this->Published = $Published;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->Published;
    }
    
    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'articles')]
    private Collection $sections;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }
    public function getAuthorUsername(): ?string
    {
        return $this->author ? $this->author->getUsername() : null;
    }
    public function getAuthorFullName(): ?string
    {
        return $this->author ? $this->author->getFullName() : null;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\SectionRepository;
use App\Repository\ArticleRepository;
class MainController extends AbstractController
{
    #[Route('/', name: 'homepage')]
public function index(SectionRepository $sectionRepository, ArticleRepository $articleRepository): Response
{
    $sections = $sectionRepository->findAll(); 
    
    // Obtener los últimos 5 artículos publicados
    $articles = $articleRepository->findBy(
        ['Published' => true],
        ['ArticleDateCreate' => 'DESC'],
        10 
    );
    
    return $this->render('main/index.html.twig', [
        'sections' => $sections,
        'articles' => $articles,  
    ]);
}
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome to my Blog!{% endblock %}

{% block body %}
{% include 'partials/nav.html.twig' %}
<div class="card mb-3">
    <h1 class="card-header bg-warning text-center">Welcome to my Blog!</h1>
    <div class="card-body bg-dark">
        <h5 class="card-title text-center">Flying around the world</h5>
    </div>
    <div class="img-fluid"></div>
</div>

{% if articles is defined and articles|length > 0 %}
    {% for article in articles %}
        <div class="card mb-3">
            <div class="card-body bg-primary">
                <h4 class="card-title text-warning">{{ article.title }}</h4>
                <h6 class="card-subtitle mb-2 text-muted"> 
                    Author: {{ article.authorFullName }} 
                    Date: {{ article.articleDateCreate|date('d/m/Y') }}
                </h6>
                <p class="card-text">{{ article.text|slice(0, 100) }}...</p>
                {% if article.sections|length > 0 %}
                    {% for section in article.sections %}
                        <a href="{{ path('section', {'slug': section.SectionSlug}) }}" class="card-link text-warning">
                            {{ section.SectionTitle }}
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="alert alert-info">No articles available.</div>
{% endif %}
{% endblock %}